### ISSUE TITLE
restart on a crash?

### ISSUE THREAD

**Issue by bosky101** [serverdensity/python-daemon#12]
what is the expected design pattern for implementing restarts on crashing?

from the documentation, it isn't apparent how to handle errors

     from daemon import Daemon
     class App(Daemon):
       def run(self):     
         try:
           foo()
         except:
           print 'crashing, so restart ?'
           daemon_runner.run()

     daemon_runner = App('/tmp/app.pid')
     daemon_runner.run()

or are restarts supposed to be handled by another process/module?

if restarts are indeed handled, an example would be great. 

thanks

**Comment by carlosperello** [comment]
As @medecau already said, that task should be handled externally with something like Supervior.
