### ISSUE TITLE
Shouldn't signal registration be outside sigtermhandler?

### ISSUE THREAD

**Issue by meatbody** [serverdensity/python-daemon#20]
def sigtermhandler(signum, frame):
        self.daemon_alive = False
        signal.signal(signal.SIGTERM, sigtermhandler)
        signal.signal(signal.SIGINT, sigtermhandler)

Shouldn't both signal.signal() calls be outside the handler? Unless I'm misunderstanding something, this is attempting to register the handler method within the handler itself.

**Comment by carlosperello** [comment]
Yep, the problem was with a previous merge that was fixing some pep8 issues that broke the indentation and the review missed that bug.

It's now fixed.
