### ISSUE TITLE
Change license to something software-compatible

### ISSUE THREAD

**Issue by nivekuil** [serverdensity/python-daemon#23]
Hi, I noticed that you're using the CC BY-SA 3.0 license here, which according to the Creative Commons [website](http://creativecommons.org/compatiblelicenses), is only compatible with other CC licenses.

```
Currently, no non-CC licenses have been designated as compatible with BY-SA 3.0.
```

The problem with CC licenses is that they aren't really intended for code, so it's unclear whether the project requires derivatives to be open source, for example. It would be great if you could change it to a more compatible license.

**Comment by carlosperello** [comment]
Problem is that we are not the original authors and the original link from where we got the code (it's on the credits section of the file) seems like is not active anymore so it's not likely we will be able to contact the original author to change it.
