### ISSUE TITLE
detach_process_context inside daemon.py hangs

### ISSUE THREAD

**Issue by madhavan020985** [serverdensity/python-daemon#24]
I am creating a context with just the pidfile argument as,
daemon.DaemonContext(pidfile="/home/user/pidfile")
And when i do context.open, the parent process dies as expected but  the detached/forked child process is not getting executed as well.

I put more logs inside daemon.py and i figured out detach_process_context is causing the problem.

``` python
def detach_process_context():
   def fork_then_exit_parent(error_message):
        try:
            pid = os.fork()
            if pid > 0:
                #the control comes here
                os._exit(0)
            #the child process control never comes here
```

i am using python-daemon (2.0.5).

**Comment by madhavan020985** [comment]
````python
import os
import time
import daemon
import os.path
import pidfile

pid = os.path.join('/var/log', 'sg_rmt_trigger_observer.pid')
context = daemon.DaemonContext(pidfile=pidfile.PidFile(pid))
with context:
  with open("log", "a") as myfile:
    myfile.write("i may never be seen")
````
this is a small snippet that can reproduce the error. I am using pip - pidfile module.

**Comment by carlosperello** [comment]
I'm sorry but I think you are not using our python-daemon but the one from https://pagure.io/python-daemon/ so we cannot help you with this issue.
