### ISSUE TITLE
isnt it on pip?

### ISSUE THREAD

**Issue by iogf** [serverdensity/python-daemon#25]
how can i install it from pip?

**Comment by brezniczky** [comment]
In case you are still interested, by trial-error looks like it's simply `pip install python-daemon`.
I was thinking this could be the case since it's mentioned at https://pypi.python.org/pypi/python-daemon/.

**Comment by amdei** [comment]
Published. See #27 
Try this now:

    pip install py_daemon

**Comment by carlosperello** [comment]
That python-daemon module on pypi is a different project.

Closing this as it's a duplicate of #17
