### ISSUE TITLE
Calling Daemon.start() immediately terminates the main process.

### ISSUE THREAD

**Issue by tribbloid** [serverdensity/python-daemon#30]
Example:

```
    class ProxyD(Daemon):

        def run(self):
           ... do something ...

    singletonProxyP = ProxyD(expanduser("~"))
    singletonProxyP.start()

    print('finished')
```

execute the above code will yield the following result:

```
Starting...

Process finished with exit code 0
```

the last line was ignored and the daemon process is not created (failed silently), not good :-<

The above behaviour was observed on Ubuntu 16.04 with Python 2.7.12

**Comment by carlosperello** [comment]
That's the full point of this module, we fork and run the code in background on a different process. If you add a big sleep call inside the run method, you should be able to see the forked process with the ps command.
