### ISSUE TITLE
test

### ISSUE THREAD

**Issue by tchene** [serverdensity/python-daemon#31]
I have the same issue, when I delete a map, nagvis delete the map but not entry in var/maplist-full-global.cfg-1.9b10-cache.

When I change maplist content to : `a:0:{}` map is deleting from sidebar

**Comment by carlosperello** [comment]
Seems like you posted this in the wrong project...

**Comment by tchene** [comment]
I'm sorry, I fork the project ans thinking that issue was in my fork only. Sorry for it.

Le 8 déc. 2016 23:00, Carlos Perelló Marín <notifications@github.com> a écrit :

Seems like you posted this in the wrong project...
