### ISSUE TITLE
ModuleNotFoundError: No module named 'daemon'

### ISSUE THREAD

**Issue by TurBoss** [serverdensity/python-daemon#42]
Hello:

  After installing the py_daemon from pip using 

```pip install py_daemon```
or
```pip install git+https://github.com/serverdensity/python-daemon.git```

into an python3 virtualenv

I'm unable to load the module

it throws 

```
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from daemon import Daemon
ModuleNotFoundError: No module named 'daemon'
```

maybe I'm doing something wrong

**Comment by TurBoss** [comment]
Ok

should be

``` from py_daemon.py_daemon import Daemon```

**Comment by kenjibailly** [comment]
Thanks, confirmed it's working!
